config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'arena#index'
  resources :gladiators
  resources :fights

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fight.rb
class Fight < ApplicationRecord

  before_create :resolve

  belongs_to :home, class_name: "Gladiator"
  belongs_to :home_weapon, class_name: "Weapon", required: false
  belongs_to :away, class_name: "Gladiator"
  belongs_to :away_weapon, class_name: "Weapon", required: false

  belongs_to :winner, class_name: "Gladiator", required: false

  has_many :turns, dependent: :destroy

  validate :not_fighting_self
  validate :winner_must_participate

  scope :fought_by, ->(gladiator) { where('home_id = :glad or away_id = :glad', glad: gladiator) }
  scope :won_by, ->(gladiator) { where(winner: gladiator) }
  scope :lost_by, ->(gladiator) { fought_by(gladiator).where.not(winner: gladiator) }
  scope :by_date, -> { order(created_at: :desc) }

  def to_s
    "#{home} #{home_weapon.present? ? "[#{home_weapon}]" : ""} VS #{away} #{away_weapon.present? ? "[#{away_weapon}]" : ""}"
  end

  private

  def not_fighting_self
    errors.add(:away, I18n.t('fight.errors.not_fighting_self')) if home == away
  end

  def winner_must_participate
    errors.add(:away, I18n.t('fight.errors.winner_must_participate')) if winner.present? and ![home,away].include?(winner)
  end

  def resolve_turn turn_no, offense, defense, weapon
    if weapon.present?
      if turn_no % weapon.speed == 0
        dmg = weapon.damage
      end
    else
      dmg = offense.damage
    end


    if dmg
      defense.current_hp -= dmg
      turns.build action: 'hit', offense: offense, defense: defense, damage: dmg
    end
  end

  def resolve
    home.current_hp = home.max_hp
    away.current_hp = away.max_hp

    turn = 0

    while !home.dead? and !away.dead?
      home_hit_chance = home.hit_chance
      away_hit_chance = away.hit_chance

      if home_hit_chance == away_hit_chance
        turns.build action: 'miss'
      elsif home_hit_chance > away_hit_chance
        resolve_turn turn, home, away, home_weapon
      else
        resolve_turn turn, away, home, away_weapon
      end

      turn += 1
    end

    self.winner = home.dead? ? away : home
  end

end

app/models/gladiator.rb
class Gladiator < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  before_create :compute_stats

  has_many :home_fights, class_name: "Fight", foreign_key: :home, dependent: :nullify
  has_many :away_fights, class_name: "Fight", foreign_key: :away, dependent: :nullify
  has_many :won_fights, class_name: "Fight", foreign_key: :winner, dependent: :nullify

  validates :name, presence: true

  attr_accessor :current_hp

  def to_s
    name
  end

  def hit_chance
    rand(1..6) + rand(1..6) + self.agility
  end

  def damage
    rand(2..self.strength)
  end

  def dead?
    @current_hp <= 0
  end

  private

  def gen_stat
    rand(1..6) + 6
  end

  def compute_stats
    self.stamina = gen_stat
    self.strength = gen_stat
    self.agility = gen_stat

    self.max_hp = (self.stamina + rand(1..6) + rand(1..6)) * 10
  end

end

app/models/turn.rb
class Turn < ApplicationRecord

  belongs_to :fight

  belongs_to :offense, class_name: "Gladiator", required: false
  belongs_to :defense, class_name: "Gladiator", required: false

end

app/models/weapon.rb
class Weapon < ApplicationRecord

  validate :damage_in_range

  def to_s
    "#{name}"
  end

  def damage
    rand(damage_low..damage_high)
  end

  private

  def damage_in_range
    errors.add(:damage_low, I18n.t('weapon.errors.damage_in_range')) if damage_low >= damage_high
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arena_controller.rb
class ArenaController < ApplicationController

  def index
  end

end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :new_fight, only: [:new, :create]
  before_action :load_fight, only: [:show]
  before_action :load_fights, only: [:index]

  def create
    if @fight.save
      flash[:success] = t(:create_success)
      redirect_to @fight
    else
      render :new
    end
  end

  private

  def permitted_attrs
    params.fetch(:fight, {}).permit(:home_id, :away_id, :home_weapon_id, :away_weapon_id)
  end

  def new_fight
    @fight = Fight.new permitted_attrs
  end

  def load_fight
    @fight = Fight.find params[:id]
  end

  def load_fights
    @fights = Fight.all
  end
end

app/controllers/gladiators_controller.rb
class GladiatorsController < ApplicationController
  before_action :new_gladiator, only: [:new, :create]
  before_action :load_gladiator, only: [:show, :edit, :update, :destroy]
  before_action :load_gladiators, only: [:index]

  def create
    if @gladiator.save
      flash[:success] = t(:create_success)
      redirect_to gladiators_path
    else
      render :new
    end
  end

  def update
    if @gladiator.update_attributes(permitted_attrs)
      flash[:success] = t(:update_success)
      redirect_to gladiators_path
    else
      render :edit
    end
  end

  def destroy
    @gladiator.destroy
    flash[:success] = t(:delete_success)
    redirect_to gladiators_path
  end

  private

  def permitted_attrs
    params.fetch(:gladiator, {}).permit(:name, :avatar)
  end

  def new_gladiator
    @gladiator = Gladiator.new permitted_attrs
  end

  def load_gladiator
    @gladiator = Gladiator.find params[:id]
  end

  def load_gladiators
    @gladiators = Gladiator.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/arena/index.html.erb
<h1>Arena</h1>

<p><%= t "welcome_msg" %></p>

<%= link_to t(:new_fight), new_fight_path, class: "btn btn-primary" %>

app/views/fights/_form.html.erb
<%= semantic_form_for @fight do |f| %>
  <div class="row">
    <div class="col-md">
      <%= f.input :home %>
    </div>
    <div class="col-md">
      <%= f.input :home_weapon %>
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <%= f.input :away %>
    </div>
    <div class="col-md">
      <%= f.input :away_weapon %>
    </div>
  </div>
  <%= f.actions do %>
    <%= f.action :submit, as: :button, button_html: { class: 'btn btn-primary' } %>
  <% end %>
<% end %>

app/views/fights/_table_fields.html.erb
<td><%= item.home %></td>
<td><%= item.away %></td>
<td><%= item.winner %></td>
<td><%= link_to t(:details), fight_path(item), class: "btn btn-primary btn-sm" %></td>

app/views/fights/_table_head.html.erb
<th><%= Fight.human_attribute_name(:home) %></th>
<th><%= Fight.human_attribute_name(:away) %></th>
<th><%= Fight.human_attribute_name(:winner) %></th>
<th width="1"></th>

app/views/fights/index.html.erb
<h1><%= Fight.model_name.human.pluralize %></h1>

<div class="actions">
  <%= link_to t(:new_fight), new_fight_path,  class: "btn btn-primary" %>
</div>

<%= render partial: "shared/table", locals: { collection: @fights } %>

<%= link_to t(:go_back), root_path %>

app/views/fights/new.html.erb
<h1><%= t(:new_resource, resource: Fight.model_name.human) %></h1>

<%= render partial: 'form' %>

<%= link_to t(:go_back), fights_path %>

app/views/fights/show.html.erb
<h1><%= @fight %></h1>

<p>
  <button class="btn btn-danger" type="button" data-toggle="collapse" data-target="#show_winner" aria-expanded="false" aria-controls="show_winner">
    <%= t '.show_winner' %>
  </button>
</p>
<div class="collapse" id="show_winner">
  <div class="card card-body">
    <%= @fight.winner %>
  </div>
</div>


<h2><%= t :details %></h2>

<ul>
<% @fight.turns.each do |turn| %>
  <li><%= t("fight.actions.#{turn.action}", offense: turn.offense, defense: turn.defense, damage: turn.damage) %></li>
<% end %>
</ul>

<%= link_to t(:go_back), root_path %>

app/views/gladiators/_form.html.erb
<%= semantic_form_for @gladiator do |f| %>
  <%= f.input :name %>
  <% if @gladiator.avatar.present? %>
    <%= image_tag @gladiator.avatar.url(:thumb) %>
  <% end %>
  <%= f.input :avatar %>
  <%= f.actions do %>
    <%= f.action :submit, as: :button, button_html: { class: 'btn btn-primary' } %>
  <% end %>
<% end %>

app/views/gladiators/_table_fields.html.erb
<td><%= item %></td>
<td><%= item.max_hp %></td>
<td><%= item.stamina %></td>
<td><%= item.strength %></td>
<td><%= item.agility %></td>
<td><%= link_to t(:details), gladiator_path(item), class: "btn btn-primary btn-sm" %></td>
<td><%= link_to t(:edit), edit_gladiator_path(item), class: "btn btn-primary btn-sm" %></td>
<td><%= link_to t(:delete), gladiator_path(item), method: :delete, class: "btn btn-danger btn-sm" %></td>

app/views/gladiators/_table_head.html.erb
<th><%= Gladiator.human_attribute_name(:name) %></th>
<th><%= Gladiator.human_attribute_name(:max_hp) %></th>
<th><%= Gladiator.human_attribute_name(:stamina) %></th>
<th><%= Gladiator.human_attribute_name(:strength) %></th>
<th><%= Gladiator.human_attribute_name(:agility) %></th>
<th width="1"></th>
<th width="1"></th>
<th width="1"></th>

app/views/gladiators/edit.html.erb
<h1><%= t(:edit_resource, resource: @gladiator) %></h1>

<%= render partial: 'form' %>

<%= link_to t(:go_back), gladiators_path %>

app/views/gladiators/index.html.erb
<h1><%= Gladiator.model_name.human.pluralize %></h1>

<div class="actions">
  <%= link_to t(:new_resource, resource: Gladiator.model_name.human), new_gladiator_path,  class: "btn btn-primary" %>
</div>

<%= render partial: "shared/table", locals: { collection: @gladiators } %>

<%= link_to t(:go_back), root_path %>

app/views/gladiators/new.html.erb
<h1><%= t(:new_resource, resource: Gladiator.model_name.human) %></h1>

<%= render partial: 'form' %>

<%= link_to t(:go_back), gladiators_path %>

app/views/gladiators/show.html.erb
<h1><%= @gladiator %></h1>

<div class="row">

  <div class="col-lg-4">
    <ul class="list-inline fight_history">
      <li class="list-inline-item"><a title="<%= t '.total_fights' %>" class="win_lose"><%= Fight.fought_by(@gladiator).count %></a></li>
      <li class="list-inline-item"><a title="<%= t '.won_fights' %>" class="win_lose win"><%= Fight.won_by(@gladiator).count %></a></li>
      <li class="list-inline-item"><a title="<%= t '.lost_fights' %>" class="win_lose loss"><%= Fight.lost_by(@gladiator).count %></a></li>
      <li class="list-inline-item"><a title="<%= t '.winrate' %>" class="win_lose"><%= number_to_percentage(Fight.won_by(@gladiator).count.to_f / Fight.fought_by(@gladiator).count * 100) %></a></li>
    </ul>
    <%= image_tag @gladiator.avatar.url(:thumb) if @gladiator.avatar.present? %>
  </div>

  <div class="col-lg">
    <ul>
      <li><strong><%= Gladiator.human_attribute_name(:max_hp) %></strong>: <%= @gladiator.max_hp %></li>
      <li><strong><%= Gladiator.human_attribute_name(:stamina) %></strong>: <%= @gladiator.stamina %></li>
      <li><strong><%= Gladiator.human_attribute_name(:strength) %></strong>: <%= @gladiator.strength %></li>
      <li><strong><%= Gladiator.human_attribute_name(:agility) %></strong>: <%= @gladiator.agility %></li>
    </ul>
  </div>

</div>

<h2><%= t '.career' %></h2>

<table class="table table-responsive">
  <thead>
    <tr>
      <th><%= t('.fight.date') %></th>
      <th><%= t('.fight.opponent') %></th>
      <th><%= t('.fight.result') %></th>
      <th width="1"></th>
    </tr>
  </thead>
  <tbody>
    <% Fight.fought_by(@gladiator).by_date.each do |fight| %>
      <tr>
        <td><%= fight.created_at %></td>
        <td><%= fight.home == @gladiator ? fight.away : fight.home %></td>
        <td><a class="win_lose <%= fight.winner == @gladiator ? "win" : "loss" %>"><%= fight.winner == @gladiator ? "W" : "L" %></a></td>
        <td><%= link_to t(:details), fight_path(fight) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Arena</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-custom">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to "Arena", root_path, class: "navbar-brand" %>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to Gladiator.model_name.human.pluralize, gladiators_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to Fight.model_name.human.pluralize, fights_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <section class="main">
      <div class="container">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>
      </div><!-- /.container -->
    </section>
  </body>
</html>

app/views/shared/_table.html.erb
<table class="table table-responsive">
  <thead>
    <tr>
      <%= render partial: "table_head" %>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |item| %>
      <tr>
        <%= render partial: "table_fields", locals: { item: item } %>
      </tr>
    <% end %>
  </tbody>
</table>